### ISSUE TITLE
config: Update more than one subdomain

### ISSUE THREAD

**Issue by benthetechguy** [maxisoft/Freenom-dns-updater#40]
I want to update the A records of `www.example.com` and `test.example.com` using `fdu process`.
I tried using this freenom.yml:
```yaml
login: test@example.com
password: test
record:
  - domain: example.com
    name: www
  - domain: example.com
    name: test
```
`fdu process` only updated the first domain and ignored the second.
